### ISSUE TITLE
Widget Layout

### ISSUE THREAD

**Issue by Jenswoltering** [avprg-soundtable/soundtable#13]
Lässt sich das Layout des Widgets anpassen? Auf den ersten Blick werden alle Elemente zentriert hinzugefügt.

**Comment by soenkelange** [comment]
Sollte dich komplett anpassen lassen. 

Von meinem iPhone gesendet

**Comment by Jenswoltering** [comment]
Lässt sich in der Tat anpassen – läuft alles!
